spring:
  application:
    name: Diary
  config:
    import: backend-module.yaml
management:
  metrics:
    export:
      influx:
        enabled: ${INFLUX_ENABLED:false}
        uri: ${INFLUX_URI:}
        org: ${INFLUX_ORGANIZATION:}
        bucket: ${INFLUX_BUCKET:}
        token: ${INFLUX_TOKEN:}