spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/diary/db;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS diary\;SET SCHEMA diary
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: false
